const char* consumer_usage_names[0x2d5] = {
"Undefined",
"Consumer Control",
"Numeric Key Pad",
"Programmable Buttons",
"Microphone",
"Headphone",
"Graphic Equalizer",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"+10",
"+100",
"AM/PM",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Power",
"Reset",
"Sleep",
"Sleep After",
"Sleep Mode",
"Illumination",
"Function Buttons",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Menu",
"Menu Pick",
"Menu Up",
"Menu Down",
"Menu Left",
"Menu Right",
"Menu Escape",
"Menu Value Increase",
"Menu Value Decrease",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Data On Screen",
"Closed Caption",
"Closed Caption Select",
"VCR/TV",
"Broadcast Mode",
"Snapshot",
"Still",
"Picture-in-Picture Toggle",
"Picture-in-Picture Swap",
"Red Menu Button",
"Green Menu Button",
"Blue Menu Button",
"Yellow Menu Button",
"Aspect",
"3D Mode Select",
"Display Brightness Increment",
"Display Brightness Decrement",
"Display Brightness",
"Display Backlight Toggle",
"Display Set Brightness to Minimum",
"Display Set Brightness to Maximum",
"Display Set Auto Brightness",
"Camera Access Enabled",
"Camera Access Disabled",
"Camera Access Toggle",
"Keyboard Brightness Increment",
"Keyboard Brightness Decrement",
"Keyboard Backlight Set Level",
"Keyboard Backlight",
"Keyboard Backlight Set Minimum",
"Keyboard Backlight Set Maximum",
"Keyboard Backlight Auto",
"Selection",
"Assign Selection",
"Mode Step",
"Recall Last",
"Enter Channel",
"Order Movie",
"Channel",
"Media Selection",
"Media Select Computer",
"Media Select TV",
"Media Select WWW",
"Media Select DVD",
"Media Select Telephone",
"Media Select Program Guide",
"Media Select Video Phone",
"Media Select Games",
"Media Select Messages",
"Media Select CD",
"Media Select VCR",
"Media Select Tuner",
"Quit",
"Help",
"Media Select Tape",
"Media Select Cable",
"Media Select Satellite",
"Media Select Security",
"Media Select Home",
"Media Select Call",
"Channel Increment",
"Channel Decrement",
"Media Select SAP",
"Reserved",
"VCR Plus",
"Once",
"Daily",
"Weekly",
"Monthly",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Play",
"Pause",
"Record",
"Fast Forward",
"Rewind",
"Scan Next Track",
"Scan Previous Track",
"Stop",
"Eject",
"Random Play",
"Select Disc",
"Enter Disc",
"Repeat",
"Tracking",
"Track Normal",
"Slow Tracking",
"Frame Forward",
"Frame Back",
"Mark",
"Clear Mark",
"Repeat From Mark",
"Return To Mark",
"Search Mark Forward",
"Search Mark Backwards",
"Counter Reset",
"Show Counter",
"Tracking Increment",
"Tracking Decrement",
"Stop/Eject",
"Play/Pause",
"Play/Skip",
"Voice Command",
"Invoke Capture Interface",
"Start or Stop Game Recording",
"Historical Game Capture",
"Capture Game Screenshot",
"Show or Hide Recording Indicator",
"Start or Stop Microphone Capture",
"Start or Stop Camera Capture",
"Start or Stop Game Broadcast",
"Start or Stop Voice Dictation Session",
"Invoke/Dismiss Emoji Picker",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Volume",
"Balance",
"Mute",
"Bass",
"Treble",
"Bass Boost",
"Surround Mode",
"Loudness",
"MPX",
"Volume Increment",
"Volume Decrement",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Speed Select",
"Playback Speed",
"Standard Play",
"Long Play",
"Extended Play",
"Slow",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Fan Enable",
"Fan Speed",
"Light Enable",
"Light Illumination Level",
"Climate Control Enable",
"Room Temperature",
"Security Enable",
"Fire Alarm",
"Police Alarm",
"Proximity",
"Motion",
"Duress Alarm",
"Holdup Alarm",
"Medical Alarm",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Balance Right",
"Balance Left",
"Bass Increment",
"Bass Decrement",
"Treble Increment",
"Treble Decrement",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Speaker System",
"Channel Left",
"Channel Right",
"Channel Center",
"Channel Front",
"Channel Center Front",
"Channel Side",
"Channel Surround",
"Channel Low Frequency Enhancement",
"Channel Top",
"Channel Unknown",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Sub-channel",
"Sub-channel Increment",
"Sub-channel Decrement",
"Alternate Audio Increment",
"Alternate Audio Decrement",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Application Launch Buttons",
"AL Launch Button Conﬁguration Tool",
"AL Programmable Button Conﬁguration",
"AL Consumer Control Conﬁguration",
"AL Word Processor",
"AL Text Editor",
"AL Spreadsheet",
"AL Graphics Editor",
"AL Presentation App",
"AL Database App",
"AL Email Reader",
"AL Newsreader",
"AL Voicemail",
"AL Contacts/Address Book",
"AL Calendar/Schedule",
"AL Task/Project Manager",
"AL Log/Journal/Timecard",
"AL Checkbook/Finance",
"AL Calculator",
"AL A/V Capture/Playback",
"AL Local Machine Browser",
"AL LAN/WAN Browser",
"AL Internet Browser",
"AL Remote Networking/ISP Connect",
"AL Network Conference",
"AL Network Chat",
"AL Telephony/Dialer",
"AL Logon",
"AL Logoff",
"AL Logon/Logoff",
"AL Terminal Lock/Screensaver",
"AL Control Panel Sel",
"AL Command Line Processor/Run",
"AL Process/Task Manager",
"AL Select Task/Application",
"AL Next Task/Application",
"AL Previous Task/Application",
"AL Preemptive Halt Task/Application",
"AL Integrated Help Center",
"AL Documents",
"AL Thesaurus",
"AL Dictionary",
"AL Desktop",
"AL Spell Check",
"AL Grammar Check",
"AL Wireless Status",
"AL Keyboard Layout",
"AL Virus Protection",
"AL Encryption",
"AL Screen Saver",
"AL Alarms",
"AL Clock",
"AL File Browser",
"AL Power Status",
"AL Image Browser",
"AL Audio Browser",
"AL Movie Browser",
"AL Digital Rights Manager",
"AL Digital Wallet",
"Reserved",
"AL Instant Messaging",
"AL OEM Features/ Tips/Tutorial Browser",
"AL OEM Help",
"AL Online Community",
"AL Entertainment Content Browser",
"AL Online Shopping Browser",
"AL SmartCard Information/Help",
"AL Market Monitor/Finance Browser",
"AL Customized Corporate News Browser",
"AL Online Activity Browser",
"AL Research/Search Browser",
"AL Audio Player",
"AL Message Status",
"AL Contact Sync",
"AL Navigation",
"AL Context-aware Desktop Assistant",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Generic GUI Application Controls",
"AC New",
"AC Open",
"AC Close",
"AC Exit",
"AC Maximize",
"AC Minimize",
"AC Save",
"AC Print",
"AC Properties",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"AC Undo",
"AC Copy",
"AC Cut",
"AC Paste",
"AC Select All",
"AC Find",
"AC Find and Replace",
"AC Search",
"AC Go To",
"AC Home",
"AC Back",
"AC Forward",
"AC Stop",
"AC Refresh",
"AC Previous Link",
"AC Next Link",
"AC Bookmarks",
"AC History",
"AC Subscriptions",
"AC Zoom In",
"AC Zoom Out",
"AC Zoom",
"AC Full Screen View",
"AC Normal View",
"AC View Toggle",
"AC Scroll Up",
"AC Scroll Down",
"AC Scroll",
"AC Pan Left",
"AC Pan Right",
"AC Pan",
"AC New Window",
"AC Tile Horizontally",
"AC Tile Vertically",
"AC Format",
"AC Edit",
"AC Bold",
"AC Italics",
"AC Underline",
"AC Strikethrough",
"AC Subscript",
"AC Superscript",
"AC All Caps",
"AC Rotate",
"AC Resize",
"AC Flip Horizontal",
"AC Flip Vertical",
"AC Mirror Horizontal",
"AC Mirror Vertical",
"AC Font Select",
"AC Font Color",
"AC Font Size",
"AC Justify Left",
"AC Justify Center H",
"AC Justify Right",
"AC Justify Block H",
"AC Justify Top",
"AC Justify Center V",
"AC Justify Bottom",
"AC Justify Block V",
"AC Indent Decrease",
"AC Indent Increase",
"AC Numbered List",
"AC Restart Numbering",
"AC Bulleted List",
"AC Promote",
"AC Demote",
"AC Yes",
"AC No",
"AC Cancel",
"AC Catalog",
"AC Buy/Checkout",
"AC Add to Cart",
"AC Expand",
"AC Expand All",
"AC Collapse",
"AC Collapse All",
"AC Print Preview",
"AC Paste Special",
"AC Insert Mode",
"AC Delete",
"AC Lock",
"AC Unlock",
"AC Protect",
"AC Unprotect",
"AC Attach Comment",
"AC Delete Comment",
"AC View Comment",
"AC Select Word",
"AC Select Sentence",
"AC Select Paragraph",
"AC Select Column",
"AC Select Row",
"AC Select Table",
"AC Select Object",
"AC Redo/Repeat",
"AC Sort",
"AC Sort Ascending",
"AC Sort Descending",
"AC Filter",
"AC Set Clock",
"AC View Clock",
"AC Select Time Zone",
"AC Edit Time Zones",
"AC Set Alarm",
"AC Clear Alarm",
"AC Snooze Alarm",
"AC Reset Alarm",
"AC Synchronize",
"AC Send/Receive",
"AC Send To",
"AC Reply",
"AC Reply All",
"AC Forward Msg",
"AC Send",
"AC Attach File",
"AC Upload",
"AC Download (Save Target As)",
"AC Set Borders",
"AC Insert Row",
"AC Insert Column",
"AC Insert File",
"AC Insert Picture",
"AC Insert Object",
"AC Insert Symbol",
"AC Save and Close",
"AC Rename",
"AC Merge",
"AC Split",
"AC Disribute Horizontally",
"AC Distribute Vertically",
"AC Next Keyboard Layout Select",
"AC Navigation Guidance",
"AC Desktop Show All Windows",
"AC Soft Key Left",
"AC Soft Key Right",
"AC Desktop Show All Applications",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"AC Idle Keep Alive",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Extended Keyboard Attributes Collection",
"Keyboard Form Factor",
"Keyboard Key Type",
"Keyboard Physical Layout",
"Vendor-Specific Keyboard Physical Layout",
"Keyboard IETF Language Tag Index",
"Implemented Keyboard Input Assist Controls",
"Keyboard Input Assist Previous",
"Keyboard Input Assist Next",
"Keyboard Input Assist Previous Group",
"Keyboard Input Assist Next Group",
"Keyboard Input Assist Accept",
"Keyboard Input Assist Cancel",
"Reserved",
"Reserved",
"Reserved",
"Privacy Screen Toggle",
"Privacy Screen Level Decrement",
"Privacy Screen Level Increment",
"Privacy Screen Level Minimum",
"Privacy Screen Level Maximum",
};
