const char* digitizer_usage_names[0xb1] = {
"Undefined",
"Digitizer",
"Pen",
"Light Pen",
"Touch Screen",
"Touch Pad",
"Whiteboard",
"Coordinate Measuring Machine",
"3D Digitizer",
"Stereo Plotter",
"Articulated Arm",
"Armature",
"Multiple Point Digitizer",
"Free Space Wand CA",
"Device Configuration",
"Capacitive Heat Map Digitizer",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Stylus",
"Puck",
"Finger",
"Device settings",
"Character Gesture",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Tip Pressure",
"Barrel Pressure",
"In Range",
"Touch",
"Untouch",
"Tap",
"Quality",
"Data Valid",
"Transducer Index",
"Tablet Function Keys",
"Program Change Keys",
"Battery Strength",
"Invert",
"X Tilt",
"Y Tilt",
"Azimuth",
"Altitude",
"Twist",
"Tip Switch",
"Secondary Tip Switch",
"Barrel Switch",
"Eraser",
"Tablet Pick",
"Touch Valid",
"Width",
"Height",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Contact Identifier",
"Device Mode",
"Device Identifier",
"Contact Count",
"Contact Count Maximum",
"Scan Time",
"Surface Switch",
"Button Switch",
"Pad Type",
"Secondary Barrel Switch",
"Transducer Serial Number",
"Preferred Color",
"Preferred Color is Locked",
"Preferred Line Width",
"Preferred Line Width is Locked",
"Latency Mode",
"Gesture Character Quality",
"Character Gesture Data Length",
"Character Gesture Data",
"Gesture Character Encoding",
"UTF8 Character Gesture Encoding",
"UTF16 Little Endian Character Gesture Encoding",
"UTF16 Big Endian Character Gesture Encoding",
"UTF32 Little Endian Character Gesture Encoding",
"UTF32 Big Endian Character Gesture Encoding",
"Capacitive Heat Map Protocol Vendor ID",
"Capacitive Heat Map Protocol Version",
"Capacitive Heat Map Frame Data",
"Gesture Character Enable",
"Transducer Serial Number Part 2 [70] SV 16.3.1",
"No Preferred Color",
"Preferred Line Style",
"Preferred Line Style is Locked",
"Ink",
"Pencil",
"Highlighter",
"Chisel Marker",
"Brush",
"No Preference ",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Digitizer Diagnostic",
"Digitizer Error",
"Err Normal Status",
"Err Transducers Exceeded",
"Err Full Trans Features Unavailable",
"Err Charge Low",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Transducer Software Info",
"Transducer Vendor Id",
"Transducer Product Id",
"Device Supported Protocols",
"Transducer Supported Protocols",
"No Protocol",
"Wacom AES Protocol",
"USI Protocol",
"Microsoft Pen Protocol",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Supported Report Rates",
"Report Rate",
"Transducer Connected",
"Switch Disabled",
"Switch Unimplemented",
"Transducer Switches",
"Transducer Index Selector",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Button Press Threshold",
};
