const char* generic_desktop_usage_names[0xE3] = {
"Undefined",
"Pointer",
"Mouse",
"Reserved",
"Joystick",
"Gamepad",
"Keyboard",
"Keypad",
"Multi-axis Controller",
"Tablet PC System Controls",
"Water Cooling Device",
"Computer Chassis Device",
"Wireless Radio Controls",
"Portable Device Control",
"System Multi-Axis Controller",
"Spatial Controller",
"Assistive Control",
"Device Dock",
"Dockable Device",
"Call State Management Control",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"X",
"Y",
"Z",
"Rx",
"Ry",
"Rz",
"Slider",
"Dial",
"Wheel",
"Hat Switch",
"Counted Buffer",
"Byte Count",
"Motion Wakeup",
"Start",
"Select",
"Reserved",
"Vx",
"Vy",
"Vz",
"Vbrx",
"Vbry",
"Vbrz",
"Vno",
"Feature Notification",
"Resolution Multiplier",
"Qx",
"Qy",
"Qz",
"Qw",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"System Control",
"System Power Down",
"System Sleep",
"System Wake Up",
"System Context Menu",
"System Main Menu",
"System App Menu",
"System Menu Help",
"System Menu Exit",
"System Menu Select",
"System Menu Right",
"System Menu Left",
"System Menu Up",
"System Menu Down",
"System Cold Restart",
"System Warm Restart",
"D-pad Up",
"D-pad Down",
"D-pad Right",
"D-pad Left",
"Index Trigger",
"Palm Trigger",
"Thumbstick",
"System Function Shift",
"System Function Shift Lock",
"System Function Shift Lock Indicator",
"System Dismiss Notiﬁcation",
"System Do Not Disturb",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"System Dock",
"System Undock",
"System Setup",
"System Break",
"System Debugger Break",
"Application Break",
"Application Debugger Break",
"System Speaker Mute",
"System Hibernate",
"System Microphone Mute",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"System Display Invert",
"System Display Internal",
"System Display External",
"System Display Both",
"System Display Dual",
"System Display Toggle Int/Ext Mode",
"System Display Swap Primary/Secondary",
"System Display Toggle LCD Autoscale",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Sensor Zone",
"RPM",
"Coolant Level",
"Coolant Critical Level",
"Coolant Pump",
"Chassis Enclosure",
"Wireless Radio Button",
"Wireless Radio LED",
"Wireless Radio Slider Switch",
"System Display Rotation Lock Button",
"System Display Rotation Lock Slider Switch",
"Control Enable",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Dockable Device Unique ID",
"Dockable Device Vendor ID",
"Dockable Device Primary Usage Page",
"Dockable Device Primary Usage ID",
"Dockable Device Docking State",
"Dockable Device Display Occlusion",
"Dockable Device Object Type",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"Call Active LED",
"Call Mute Toggle",
"Call Mute LED",
};
